### PR TITLE
Ollama changes and manager_llm addition

### PR DESCRIPTION
**Pull request by sjdthree**
I've added Ollama and llama2 local llm running.
also added a "manager_llm" and hierarchical to attempt a task monitor to ensure it doesn't run forever and also doesn't request the same thing.  that part isn't working yet.

### CODE REVIEW

**Comment by AbubakrChan** [comment]
Thanks for the PR, appreciate it!
will check it out.

**Comment by sjdthree** [comment]
After taking another look, it has 5 changes:
1) Ollama for local
2) Addition of a second "taskmanagerllm" model
3) A timer to show how long the run took (I find I just let it run in the background and come back to it, so I always want to know)
4) Limit the max_iter to 2, default is 15.
5) Hierarchical Process running to test if my "Project Manager" role would control the output.

If you want, I can just cut it down to only Ollama for this PR.

**Comment by AbubakrChan** [comment]
Yeah, I think only the 1, 3 would be great for now.

Thank you!

**Comment by AbubakrChan** [comment]
Loved it!
Thanks

**Pull request merged**
